apiVersion: v1
kind: Secret
metadata:
  name: runner-secret
type: Opaque
data:
  ## git_service_token 访问私有项目如(oss-internal)需要,需要进行base64编码一下，echo -n "qKutsfEY4x8Y4Gr8P2tL" | base64
  GIT_SERVICE_TOKEN: cUt1dHNmRVk0eDhZNEdyOFAydEw=